# generated by zon2nix (https://github.com/Cloudef/zig2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:
with builtins;
with lib; let
  unpackZigArtifact = {
    name,
    artifact,
  }:
    runCommandLocal name {nativeBuildInputs = [zig];} ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig = {
    name,
    url,
    hash,
  }: let
    artifact = fetchurl {inherit url hash;};
  in
    unpackZigArtifact {inherit name artifact;};

  fetchGitZig = {
    name,
    url,
    hash,
    rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
  }: let
    parts = splitString "#" url;
    url_base = elemAt parts 0;
    url_without_query = elemAt (splitString "?" url_base) 0;
  in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact = {
    name,
    url,
    hash,
    ...
  } @ args: let
    parts = splitString "://" url;
    proto = elemAt parts 0;
    path = elemAt parts 1;
    fetcher = {
      "git+http" = fetchGitZig (
        args
        // {
          url = "http://${path}";
        }
      );
      "git+https" = fetchGitZig (
        args
        // {
          url = "https://${path}";
        }
      );
      http = fetchZig {
        inherit name hash;
        url = "http://${path}";
      };
      https = fetchZig {
        inherit name hash;
        url = "https://${path}";
      };
    };
  in
    fetcher.${proto};
in
  linkFarm name [
    {
      name = "known_folders-0.0.0-Fy-PJtLDAADGDOwYwMkVydMSTp_aN-nfjCZw6qPQ2ECL";
      path = fetchZigArtifact {
        name = "known_folders";
        url = "git+https://github.com/ziglibs/known-folders.git#aa24df42183ad415d10bc0a33e6238c437fc0f59";
        hash = "sha256-YiJ2lfG1xsGFMO6flk/BMhCqJ3kB3MnOX5fnfDEcmMY=";
        rev = "aa24df42183ad415d10bc0a33e6238c437fc0f59";
      };
    }
    {
      name = "12207ffcc21b74386d241268719cffdd9ac124932f368286fa5deda1e0d230b41a53";
      path = fetchZigArtifact {
        name = "tomlz";
        url = "git+https://github.com/mattyhall/tomlz.git#bb7706fb5a752526f74ce544fc15125be8e58495";
        hash = "sha256-eZ5oyona/IkFuQ7WfP8vsQcvXr+I39scDFk5X0au4Fw=";
        rev = "bb7706fb5a752526f74ce544fc15125be8e58495";
      };
    }
    {
      name = "cli-0.9.0-2eKe_zP5AAD96LcpU9Gdo7vRHvHIKjYnyR9ME6si527r";
      path = fetchZigArtifact {
        name = "cli";
        url = "git+https://github.com/sam701/zig-cli#9fca749122a321fd4af4fecafba0062b3e36db98";
        hash = "sha256-PCuRlECGRWPTW2MtkUc4X4dKieVg4Ji4J4uHWJhxpL0=";
        rev = "9fca749122a321fd4af4fecafba0062b3e36db98";
      };
    }
  ]
