# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "122068053f0658600ad5cb5023b45a203c422a6c263dd150b55a98abcf1ad0ce68b4";
    path = fetchzip {
      url = "https://github.com/Strix-Vyxlor/zig-json/archive/refs/tags/0.1.3.tar.gz";
      hash = "sha256-30VHwomq3NmjBrIBcc4vpp85HtgOc2ATqBij6M7ncIs=";
    };
  }
  {
    name = "12209d2738a2e1dbd3781c2e5f01a2ea877dcfeea53efdfa1913247297d328e6b207";
    path = fetchzip {
      url = "https://github.com/ziglibs/known-folders/archive/47076c6b11214a218e9244471d8762310820911a.tar.gz";
      hash = "sha256-t9mDlK5MCoAu020O5Z0X9yOxO9yPYPuub7olP//OWtc=";
    };
  }
  {
    name = "1220ab73fb7cc11b2308edc3364988e05efcddbcac31b707f55e6216d1b9c0da13f1";
    path = fetchzip {
      url = "https://github.com/sam701/zig-cli/archive/9a94c4803a52e54c26b198096d63fb5bde752da2.tar.gz";
      hash = "sha256-z0qWjYLu7RJb8rGFHOxzaTA+taD4jz0AcV19YgEJA9s=";
    };
  }
]
